### ISSUE TITLE
ROSの環境変数設定がおかしい

### ISSUE THREAD

**Issue by ShunjiHashimoto** [ShunjiHashimoto/cugo#36]

**Comment by ShunjiHashimoto** [comment]
現在のROS環境変数設定の確認
export | grep ROS

**Comment by ShunjiHashimoto** [comment]
python pathを通すと以下のエラーが出る
```gedit
# source /opt/ros/melodic/setup.bash
export ROS_MASTER_URI=http://localhost:11311
export ROS_HOSTNAME=localhost
alias cw='cd ~/catkin_ws'
alias cs='cd ~/catkin_ws/src'
# alias cm='cd ~/catkin_ws && catkin_make'
alias cm='catkin build'
**export PYTHONPATH=/home/hashimoto/.local/lib/python3.6/site-packages**
source /opt/ros/melodic/setup.bash
source ~/catkin_ws/devel/setup.bash
```

```bash
Traceback (most recent call last):
  File "/opt/ros/melodic/bin/rostopic", line 34, in <module>
    import rostopic
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rostopic/__init__.py", line 60, in <module>
    import genpy
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genpy/__init__.py", line 34, in <module>
    from . message import Message, SerializationError, DeserializationError, MessageException, struct_I
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genpy/message.py", line 64, in <module>
    import numpy as np
  File "/home/hashimoto/.local/lib/python3.6/site-packages/numpy/__init__.py", line 292
SyntaxError: Non-ASCII character '\xef' in file /home/hashimoto/.local/lib/python3.6/site-packages/numpy/__init__.py on line 293, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

```
