### ISSUE TITLE
installnihituyounamono

### ISSUE THREAD

**Issue by ShunjiHashimoto** [ShunjiHashimoto/cugo#4]

**Comment by ShunjiHashimoto** [comment]
sudo apt-get install ros-melodic-joy
sudo apt-get install python-rpi.gpio

**Comment by ShunjiHashimoto** [comment]
```bash
ubuntu@raspi:~/catkin_ws/src/tang/tang_bringup/launch$ roslaunch tang_detection tang_detection.launch
... logging to /home/ubuntu/.ros/log/e9b158d2-0898-11ec-a92b-dca632707892/roslaunch-raspi-5589.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://localhost:37875/

SUMMARY
========

PARAMETERS
 * /rosdistro: melodic
 * /rosversion: 1.14.11
 * /tang_detection/video_path: /home/hashimoto/V...

NODES
  /
    tang_detection (tang_detection/redanddnn_detection.py)

auto-starting new master
process[master]: started with pid [5601]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to e9b158d2-0898-11ec-a92b-dca632707892
process[rosout-1]: started with pid [5612]
started core service [/rosout]
process[tang_detection-2]: started with pid [5616]
Traceback (most recent call last):
  File "/home/ubuntu/catkin_ws/src/tang/tang_detection/scripts/redanddnn_detection.py", line 7, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
[tang_detection-2] process has died [pid 5616, exit code 1, cmd /home/ubuntu/catkin_ws/src/tang/tang_detection/scripts/redanddnn_detection.py __name:=tang_detection __log:=/home/ubuntu/.ros/log/e9b158d2-0898-11ec-a92b-dca632707892/tang_detection-2.log].                                                                                                                             
log file: /home/ubuntu/.ros/log/e9b158d2-0898-11ec-a92b-dca632707892/tang_detection-2*.log                                    
^C[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done

```

**Comment by ShunjiHashimoto** [comment]
ubuntu@raspi:~$ pip3 install numpy

Command 'pip3' not found, but can be installed with:

sudo apt install python3-pip

**Comment by ShunjiHashimoto** [comment]
```bash
ubuntu@raspi:~$ sudo apt install python3-pip
E: Could not get lock /var/lib/dpkg/lock-frontend - open (11: Resource temporarily unavailable)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?

```

**Comment by ShunjiHashimoto** [comment]
ROSの署名が古いので以下のサイトを参考にコマンド実行
https://qiita.com/seigot/items/40e69270466eafaaacfd

**Comment by ShunjiHashimoto** [comment]
```bash
ubuntu@raspi:~$ sudo apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
Executing: /tmp/apt-key-gpghome.PVwlK3SQp2/gpg.1.sh --keyserver hkp://keyserver.ubuntu.com:80 --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
gpg: key F42ED6FBAB17C654: "Open Robotics <info@osrfoundation.org>" 1 new signature
gpg: Total number processed: 1
gpg:         new signatures: 1
```

**Comment by ShunjiHashimoto** [comment]
https://github.com/ShunjiHashimoto/cugo/issues/8
https://www.komee.org/entry/2018/10/26/120000
nokorehatobasita
```bash
$ sudo apt -y install build-essential \
cmake git libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev \
python-dev python-numpy libtbb2 libtbb-dev libjpeg-dev libpng-dev libtiff-dev libdc1394-22-dev
```

**Comment by ShunjiHashimoto** [comment]
```bash
ubuntu@raspi:~$ roslaunch tang_detection tang_detection.launch 
... logging to /home/ubuntu/.ros/log/1bfbfe42-08a2-11ec-a460-dca632707892/roslaunch-raspi-3590.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://localhost:43315/

SUMMARY
========

PARAMETERS
 * /rosdistro: melodic
 * /rosversion: 1.14.11
 * /tang_detection/video_path: /home/ubuntu/catk...

NODES
  /
    tang_detection (tang_detection/redanddnn_detection.py)

auto-starting new master
process[master]: started with pid [3601]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 1bfbfe42-08a2-11ec-a460-dca632707892
process[rosout-1]: started with pid [3612]
started core service [/rosout]
process[tang_detection-2]: started with pid [3615]
Traceback (most recent call last):
  File "/home/ubuntu/catkin_ws/src/tang/tang_detection/scripts/redanddnn_detection.py", line 10, in <module>
    import rospy
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/__init__.py", line 49, in <module>
    from .client import spin, myargv, init_node, \
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/client.py", line 52, in <module>
    import roslib
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslib/__init__.py", line 50, in <module>
    from roslib.launcher import load_manifest  # noqa: F401
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslib/launcher.py", line 42, in <module>
    import rospkg
ModuleNotFoundError: No module named 'rospkg'
[tang_detection-2] process has died [pid 3615, exit code 1, cmd /home/ubuntu/catkin_ws/src/tang/tang_detection/scripts/redanddnn_detection.py __name:=tang_detection __log:=/home/ubuntu/.ros/log/1bfbfe42-08a2-11ec-a460-dca632707892/tang_detection-2.log].
log file: /home/ubuntu/.ros/log/1bfbfe42-08a2-11ec-a460-dca632707892/tang_detection-2*.log
^C[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done

```

**Comment by ShunjiHashimoto** [comment]
solution
https://github.com/ShunjiHashimoto/cugo/issues/21#issuecomment-897602739
